### ISSUE TITLE
Failed to run my own server

### ISSUE THREAD

**Issue by MattiaRigi97** [jina-ai/dalle-flow#1]
Hi, i'm trying to run my own server following the steps in the repo but I've the following error:

![jinaerror](https://user-images.githubusercontent.com/45123055/166965089-556dac32-a44d-4fd4-8fc4-678ca8ec1cd9.png)

I'm on AWS Sagemaker console.. I tried with a ml.g4dn.16xlarge to avoid having resource issues as I thought it was related to that.

Can you help me to solve this issue?

**Comment by windmaple** [comment]
There is sth. weird with JAX installation. Could you do 'pip install -U jax[cuda] flax' and then run it again?

**Comment by huanghaifeng1234** [comment]
Enviroment: docker image with 'Linux 3b017f71c659 4.15.0-88-generic'
after running  'pip install -U jax[cuda] flax', then run 'jina flow --uses flow.yml', I get error:
![image](https://user-images.githubusercontent.com/81546069/167248985-7d41cd4b-f053-4a35-baf2-7c0a31e57a5c.png)
![image](https://user-images.githubusercontent.com/81546069/167248991-11c12ef3-13bf-4910-aae9-2bb15f365d14.png)
![image](https://user-images.githubusercontent.com/81546069/167249012-365ce499-0ff8-4468-b474-dbc87f57bed9.png)

**Comment by hanxiao** [comment]
dalle flow is untested on CPU, also not recommend to run on CPU, it is too computational demanding.

Your error suggests you are trying to run JAX on a CPU machine

**Comment by huanghaifeng1234** [comment]
Actually I'm running in a GPU machine, although I'm running in a docker container, which I run with argument 'docker run --gpus all'



---Original---
From: "Han ***@***.***&gt;
Date: Sat, May 7, 2022 22:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jina-ai/dalle-flow] Failed to run my own server (Issue #1)




 
dalle flow is untested on CPU, also not recommend to run on CPU, it is too computational demanding.
 
Your error suggests you are trying to run JAX on a CPU machine

**Comment by hanxiao** [comment]
maybe jax is too old? try pip install -U jax in docker?

**Comment by windmaple** [comment]
> 

CPU definitely doesn't work. I can attest to that :)

**Comment by hanxiao** [comment]
There are some caveats you may encounter when deploying your own server:

- You will need at least 2 GPU. One for DALLE mega one for GLID3 XL.
- Make sure you have [all files & folders structured as described here](https://github.com/jina-ai/dalle-flow#clone-repos)
- The first time downloading DALLE mega will take some time, my average speed internet takes 10 min.

**Comment by huanghaifeng1234** [comment]
Hi, I have 8 GPU, and files and folders have been structured as described. After I do ' pip install -U jax' and upgrade jaxlab to 0.3.7, it generated error:
![image](https://user-images.githubusercontent.com/81546069/167336565-d856dfd8-a800-4066-bd46-227e310d29d4.png)
I searched this error in stackflow and I got this:
[isin error](https://stackoverflow.com/questions/72109033/cannot-import-name-isin-python)

I installed with 'pip install jax==0.3.4 jaxlib==0.3.2' but it didn't help, it generated this error:
![image](https://user-images.githubusercontent.com/81546069/167336951-3dce57a0-93ec-48b8-8882-3c291f026d7d.png)

So I wonder which version of jax and jaxlib you are using.

**Comment by hanxiao** [comment]
i see, let me work on an official Dockerfile today.

**Comment by huanghaifeng1234** [comment]
Thanks for your help

**Comment by wstrinz** [comment]
I ran into just about the same sequence of errors trying to run this on a Debian 11 GCloud Compute Engine VM.

To get the `PrecisionLike` import working (after install the jax/jaxlib versions mentioned in https://github.com/jina-ai/dalle-flow/issues/1#issuecomment-1120607507), I installed the latest flax version from Github with:

```
pip install --upgrade git+https://github.com/google/flax.git
```

And now the jina flow builds/starts successfuly!

**Comment by huanghaifeng1234** [comment]
install latest flax and jax version from github follewed by 'pip install --upgrade jaxlib' worked for me, thanks!

**Comment by huanghaifeng1234** [comment]
after I deployed my own server and I changed the server_url to 'grpc://0.0.0.0:51005' in my client.py like
![image](https://user-images.githubusercontent.com/81546069/167541090-8e5e40b0-dc0b-46eb-9bb2-d3b66b843250.png)

server has received the request but the client.py was stuck like forever
![image](https://user-images.githubusercontent.com/81546069/167541219-8d59e6a8-1d99-44a2-b6df-5e7ae5dae0b0.png)

after I pressed Ctrl+C to stop it, I get trace back information:
![image](https://user-images.githubusercontent.com/81546069/167541459-cfaae31f-b737-4d9e-9b5a-54c68cc1ec8a.png)

and I found that the output image was not saved as expected, whether my writing form of 'grpc://0.0.0.0:51005' is correct?

**Comment by hanxiao** [comment]
guys, im almost ready with my dockerfile, see #7 still last check.

**Comment by hanxiao** [comment]
yes! it works with CUDA 11.6 out of the box! I'm going to write some README and merge into master!

**Comment by hanxiao** [comment]
It's done! Give it try, open new issue if you have problems

**Comment by huanghaifeng1234** [comment]
Nope, still need the official help



---Original---
From: "Jinke ***@***.***&gt;
Date: Wed, May 11, 2022 20:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jina-ai/dalle-flow] Failed to run my own server (Issue #1)




 
@huanghaifeng1234 Hi, I am also having this issue. The server received and processed the request but the client seemed to get stuck. Was this solved?
