### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by RHODOK** [jina-ai/dalle-flow#100]
When running natively or using Docker container I receive the error as per traceback:

```
/dalle/glid-3-xl/dalle_flow_glid3/sample.py:19 in do_run                                                                                               
       │                                                                                                                                                        
       │    16 │   text_blank = blank_bert_embedding.repeat(runtime_args.batch_size, 1, 1)                                                                      
       │    17 │                                                                                                                                                
       │    18 │   # clip context                                                                                                                               
       │ ❱  19 │   text_emb_clip = np.repeat(text_emb_clip[np.newaxis, :], runtime_args.batch_size,                                                            
       │       axis=0)
```
       
text_emb_clip is not being populated, been trying to run pdb's in the native version but that seems to create a lot of issues on it's own.
  
It runs fine when glid-3 is disabled, but it then loses some of the power of the flow and mainly just results in me running stable diffusion.

This is running in WSL2 so possibly that may be creating issues, though it isn't clear to me at the moment how.

Will continue trying to debug, but thought it might be useful to know, especially in the case of docker failing.

**Comment by delgermurun** [comment]
Need to provide embedding from previous step.
https://github.com/jina-ai/dalle-flow#step-2-select-and-refinement-via-glid3-xl
```python
fav_id = 3
fav = da[fav_id]
fav.embedding = doc.embedding
fav.display()
```

`fav.embedding = doc.embedding` is important one.

**Comment by RHODOK** [comment]
This doesn't exist, the first model hit is the glid, i.e. this error occurs before that step on line:

```
doc = Document(text=prompt).post(server_url, parameters={'num_images': 8})
```

**Comment by delgermurun** [comment]
hmmm. Do you have `clip_encoder` executor before `diffusion`?

**Comment by CryptoSoltan** [comment]
hey I have the same error
TypeError: 'NoneType' object is not subscribable
how can I fix it
My install version is updated but it can not interrogate the image or restore faces and it keep showing me this

**Comment by JoanFM** [comment]
Hey @CryptoSoltan,

Do you have clip encoder executor before diffusion?

**Comment by CryptoSoltan** [comment]
> 

I don't even know what that means lol
I did everything based on a tutorial on youtube 
Im not sure what's causing this problem on my computer

**Comment by CryptoSoltan** [comment]
oh I just saw that 
and I have 0 knowledge of coding 
I'm a 3d artist 
I will give it a try
thank you

**Comment by JoanFM** [comment]
Can you provide a `step-by-step` description of what u have done that leads to this error?

**Comment by CryptoSoltan** [comment]
I have installed python(addpython.exe to the path has been checked) and git
then I copied the git clone and install the stable diffusion 1.5
then I've downloaded the model from hugging face (changed the name to model after download and put it in the model folder .
![image](https://user-images.githubusercontent.com/89420883/197535837-bb165dc6-a44c-41d8-b3a0-67b14e2ed978.png)

**Comment by CryptoSoltan** [comment]
basically I've done everything in the video 
https://www.youtube.com/watch?v=ARgcVrNpKHs&list=PLkIRB85csS_sxKXvJ9xC8m33zKqKGFNtn

**Comment by CryptoSoltan** [comment]
basically I've followed this tutorial which is the lasted one
https://www.youtube.com/watch?v=ycQJDJ-qNI8

**Comment by CryptoSoltan** [comment]
ive tried another one before and it didn't work too

**Comment by CryptoSoltan** [comment]
> Can you provide a `step-by-step` description of what u have done that leads to this error?

do I have to install something for that to work?

**Comment by CryptoSoltan** [comment]
> Can you provide a `step-by-step` description of what u have done that leads to this error?

after the installation everything thing seems to woking fine but the interrogate button keeps showing error
![image](https://user-images.githubusercontent.com/89420883/197536804-51ddf873-de80-45fc-a43a-4a2e2b5bf5b8.png)
![image](https://user-images.githubusercontent.com/89420883/197536856-3f040d96-6a2c-49cc-b408-c88c1b8e0975.png)

**Comment by JoanFM** [comment]
Hey @CryptoSoltan ,

you are using a project which is not the one of this repository, so there is nothing we can do to help you

**Comment by CryptoSoltan** [comment]
Also this doesn't work too
![image](https://user-images.githubusercontent.com/89420883/197537114-d648ad5f-20ee-4780-a2cc-cbf5910c5c0c.png)

**Comment by CryptoSoltan** [comment]
> Hey @CryptoSoltan ,
> 
> you are using a project which is not the one of this repository, so there is nothing we can do to help you

oh I see 
thank you

**Comment by JoanFM** [comment]
I will close the error as there has not been interaction for long time. Feel free to open with more details if probelm encountered again
