### ISSUE TITLE
Windows instructions?

### ISSUE THREAD

**Issue by MSDNAndi** [jina-ai/dalle-flow#107]
It would be nice if you could provide windows instructions. Various commands do not work on Windows without additional steps (including opening ports).

**Comment by delgermurun** [comment]
Hello @MSDNAndi,

Thank you for trying out DALL·E Flow. Sorry that you're having trouble running it on Windows.
As we do not have expertise in the Windows environment, we cannot do much about it. I'm sorry about that.

As open source software, we rely heavily on community contributions.
Therefore, if you are able to run Dalle-Flow on a Windows machine, a PR for instructions would be greatly appreciated. Thank you very much.
