### ISSUE TITLE
jaxlib not found

### ISSUE THREAD

**Issue by MSDNAndi** [jina-ai/dalle-flow#108]
When launching
jina flow --uses flow.tmp.yml
jax seems to fail because jaxlib is not found. All requirements / pip install seem to be satisfied.

Platform: Windows.
Used conda for environments.

ERROR  dalle/rep-0@144956 ImportError('can not import module from                                    [09/13/22 16:49:02]
       D:\\Dev\\AIModels\\Diffusion\\dalle\\dalle-flow\\executors\\dalle\\executor\\__init__.py')
       during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization
        add "--quiet-error" to suppress the exception details
       ╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
       │ C:\Users\andre\anaconda3\envs\dalleflow\lib\site-packages\jax\_src\lib\__init__.py:53 in  │
       │ <module>                                                                                  │
       │                                                                                           │
       │    50 del _signal                                                                         │
       │    51                                                                                     │
       │    52 try:                                                                                │
       │ ❱  53   import jaxlib as jaxlib                                                           │
       │    54 except ModuleNotFoundError as err:                                                  │
       │    55   raise ModuleNotFoundError(                                                        │
       │    56 │   'jax requires jaxlib to be installed. See '                                     │
       ╰───────────────────────────────────────────────────────────────────────────────────────────╯
       ModuleNotFoundError: No module named 'jaxlib'

**Comment by delgermurun** [comment]
https://github.com/jina-ai/dalle-flow/issues/107#issuecomment-1246525091
