### ISSUE TITLE
Switch to a faster, more memory efficient version of the stable-diffusion library

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [jina-ai/dalle-flow#110]
That repo does not appear to be maintained:

https://github.com/CompVis/stable-diffusion/issues/260

I have started my own repo with an emphasis on purity and optimizations:

https://github.com/AmericanPresidentJimmyCarter/stable-diffusion

**Comment by delgermurun** [comment]
How about https://github.com/huggingface/diffusers? Should we switch to this?
Looks like really simple to use.

**Comment by AmericanPresidentJimmyCarter** [comment]
I would need to tear out and rewrite all of my code. I've known about the existence of the library since it was created but compared to the origin compvis lib I found that the diffusers lib was too abstracted and gets performance updates later or never compared to some of the more popular libraries like lstein/neonsecret/automatic1111.

**Comment by AmericanPresidentJimmyCarter** [comment]
My library is already faster than this one too. Getting 15 it/s with it on a 3090.
