### ISSUE TITLE
Error with stable-diffusion model - FileNotFoundError

### ISSUE THREAD

**Issue by Tyler2ee** [jina-ai/dalle-flow#124]
Hi, 
I tried to install stable diffusion model to my local server, but I encountered this error when I run 
`jina flow --uses flow.tmp.yml`

`FileNotFoundError: [Errno 2] No such file or directory: '/home/tyler/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/refs/main'`

Also I tried this simple script too. 

```python
from stable_inference import StableDiffusionInference

stable_diffusion_module = StableDiffusionInference(
    checkpoint_loc='PATH',
    height=512,
    max_n_subprompts=8,
    max_resolution=589824,
    n_iter=1,
    use_half=True,
    width=512,
)
```
but the same error happened. 
I used this lib for stable-inference.
stable-inference @ git+https://github.com/AmericanPresidentJimmyCarter/stable-diffusion.git@v0.0.11

**Comment by AmericanPresidentJimmyCarter** [comment]
It should download that automatically on first run if it's not there, since it needs it for the tokenizer/embedder.

**Comment by AmericanPresidentJimmyCarter** [comment]
See: https://github.com/AmericanPresidentJimmyCarter/stable-diffusion/blob/main/src/ldm/modules/encoders/modules.py#L235-L250

As it's from `transformers`, it's odd that it didn't simply download.

**Comment by JoanFM** [comment]
this `local_files_only=True` seems odd @AmericanPresidentJimmyCarter ?

**Comment by AmericanPresidentJimmyCarter** [comment]
Yeah, that must be it. I will remove it in my repo later today and bump the version. @Tyler2ee for now just open `python` and 

```py
version = 'openai/clip-vit-large-patch14'
self.tokenizer = CLIPTokenizer.from_pretrained(version)
self.transformer = CLIPTextModel.from_pretrained(version)
```

That should download the models.

**Comment by JoanFM** [comment]
Please @AmericanPresidentJimmyCarter , can you please let us know when this is bumped on your end?
