### ISSUE TITLE
Multi-GPU doesn't work due to hard coded replicas value

### ISSUE THREAD

**Issue by Kadah** [jina-ai/dalle-flow#126]
Setting the various CUDA_VISIBLE_DEVICES to more than 1 GPU doesn't result in them getting used due to replicas being hardcoded to 1. Setting replicas to >1 allows flow to make use of more GPUs.

**Comment by JoanFM** [comment]
As explained here https://docs.jina.ai/fundamentals/flow/topologies/#replicate-on-multiple-gpus

This is expected, setting this env var will affect how each replica is assigned a GPU. So I would say this works as expected
