### ISSUE TITLE
Command jina flow --uses flow.yml is not completing the job

### ISSUE THREAD

**Issue by spuliz** [jina-ai/dalle-flow#14]
Following your step by step guide for setting up my own server is taking forever. 
My jina flow --uses flow.yml is running since 1 hour and is blocked at 4/6 (see screenshot). 

<img width="834" alt="image" src="https://user-images.githubusercontent.com/15948985/168438506-8bfc8c0b-7940-4c25-aae2-86f21bec65bf.png">

**Comment by acheong08** [comment]
Check out issue #1 or maybe use docker

**Comment by spuliz** [comment]
That was an issue with my GPU not powerful enough.
