### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AstroCrashed** [jina-ai/dalle-flow#145]
Dont know what the error is 
![image](https://user-images.githubusercontent.com/102970299/209174322-a68f4577-498b-45b4-937e-0c432739817c.png)
![2022-12-22_21h34_36](https://user-images.githubusercontent.com/102970299/209174439-c1a65dd9-12f3-4a94-924e-51a2b0b26aa7.png)

ERROR  GRPCClient@2502 gRPC error: StatusCode.UNAVAILABLE HTTP Balancer service in fail-fast    [12/22/22 16:06:04]
       |Gateway: Communication error with deployment diffusion at address(es)                                      
       {'diffusion.jnamespace-6ac51e74de.svc:8080'}. Head or worker(s) may be down.                                
       The ongoing request is terminated as the server is not available or closed already.                         

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/base/grpc.py", line 220, in _get_results
    async for resp in self._stream_rpc(
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/base/grpc.py", line 78, in _stream_rpc
    async for resp in stub.Call(
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "HTTP Balancer service in fail-fast |Gateway: Communication error with deployment diffusion at address(es) {'diffusion.jnamespace-6ac51e74de.svc:8080'}. Head or worker(s) may be down."
	debug_error_string = "{"created":"@1671725164.783378402","description":"Error received from peer ipv4:44.212.139.161:443","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"HTTP Balancer service in fail-fast |Gateway: Communication error with deployment diffusion at address(es) {'diffusion.jnamespace-6ac51e74de.svc:8080'}. Head or worker(s) may be down.","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/jina/helper.py", line 1315, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/mixin.py", line 266, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/base/grpc.py", line 259, in _get_results
    raise ConnectionError(my_details)
ConnectionError: HTTP Balancer service in fail-fast |Gateway: Communication error with deployment diffusion at address(es) {'diffusion.jnamespace-6ac51e74de.svc:8080'}. Head or worker(s) may be down.

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.8/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1329             try:
-> 1330                 return thread.result
   1331             except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)

<timed exec> in <module>

3 frames

[/usr/local/lib/python3.8/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1332                 from jina.excepts import BadClient
   1333 
-> 1334                 raise BadClient(
   1335                     'something wrong when running the eventloop, result can not be retrieved'
   1336                 )

BadClient: something wrong when running the eventloop, result can not be retrieved

**Comment by JoanFM** [comment]
Hello @AstroCrashed , what exact command are you running?

**Comment by JoanFM** [comment]
Hey @AstroCrashed,

I have reproduced the issue as it seems there is an Executor down

**Comment by JoanFM** [comment]
Hello @AstroCrashed,

the server is back up, you should be able to run the snippet now
