### ISSUE TITLE
ERROR in Google colab - is this even still maintained?

### ISSUE THREAD

**Issue by fbauer-kunbus** [jina-ai/dalle-flow#146]
Step [1] creates the following ERROR:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
tensorflow-metadata 1.12.0 requires protobuf<4,>=3.13, but you have protobuf 4.21.12 which is incompatible.
tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
grpcio-status 1.48.2 requires grpcio>=1.48.2, but you have grpcio 1.47.2 which is incompatible. 
```

Setting values in steps [2] and [3] works, step [4] is non-existent (is this deliberately so, or does it follow from error in step [1]?) and step [5] is crashing with:

```
File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1674645596.096278089","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1674645596.096277519","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
```

and other subsequent errors. Please check ...

**Comment by hanxiao** [comment]
For the sake of cost-efficiency, we shutdown the demo server on our side, so u will need to deploy one by yourself.

**Comment by fbauer-kunbus** [comment]
This is an understandable motive - but shouldn't this be mentioned on the Colab page somewhere? Am I overlooking something?

**Comment by alexcg1** [comment]
Fixed by #147 . It now displays in the readme at the top

**Comment by fbauer-kunbus** [comment]
Nice - but what if I came directly to the Colab page ... ? 
Please update this also: https://colab.research.google.com/github/jina-ai/dalle-flow/blob/main/client.ipynb

Thnx!

**Comment by alexcg1** [comment]
Fixed in #148

**Comment by fbauer-kunbus** [comment]
Maybe I get something wrong - but is there ANY hint **on the Google Colab page**, that the notebook ONLY works if you have an **own demo server**? 
The notepad still says:
"We have provided a demo server for you to play:" with the default value of 'grpcs://dalle-flow.dev.jina.ai'
**Which obviously doesn't work!**
My only request left is that this fact is reflected anywhere on the notebook page! The last history entry at the top, just below the colorful Dall-E Flow image is from **2022/8/8**

**Comment by JoanFM** [comment]
@alexcg1 can you please check?

**Comment by fbauer-kunbus** [comment]
Great - now it is mentioned at the very top of the Colab notebook ... thank you!
