### ISSUE TITLE
Docker Container Won't Run "error waiting for container: context canceled"

### ISSUE THREAD

**Issue by 6630507** [jina-ai/dalle-flow#16]
Running Ubuntu 20.04 with an RTX 3090.

Docker container builds successfully, but will not run.

> Successfully built 0ec2f71b358c
> Successfully tagged jinaai/dalle-flow:latest
> dalle-flow$ docker run -p 51005:51005 -v $HOME/.cache:/root/.cache --gpus all jinaai/dalle-flow
> docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> ERRO[0000] error waiting for container: context canceled

**Comment by fuyunfei** [comment]
This may occur as you don't install nvidia-container-toolkit, simply type this command in terminal as:

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
sudo systemctl restart docker

**Comment by 6630507** [comment]
Thanks for the quick response.

I installed the nvidia-docker package and update my system to CUDA 11.6, but my docker image now terminates with "RuntimeFailToStart."

The docker image throws the following errors:



> CRITI… dalle/rep-0@14 can not load the executor from         [05/17/22 17:17:16]
>        executors/dalle/config.yml                                               
> ERROR  dalle/rep-0@14 ImportError('can not import module     [05/17/22 17:17:16]
>        from /dalle/dalle-flow/executors/dalle/dm_helper.py')                    
>        during <class                                                            
>        'jina.serve.runtimes.worker.WorkerRuntime'>        

                      


>        AttributeError: module 'jaxlib.cuda_linalg' has no                       
>        attribute 'cuda_lu_pivots_to_permutation'         

                       


>        ImportError: can not import module from                                  
>        /dalle/dalle-flow/executors/dalle/dm_helper.py

**Comment by spuliz** [comment]
Same issues

**Comment by 6630507** [comment]
The dockerfile was recently changed to specify an nvidia-docker package on install.  I did a git-pull and nuked my conda installation and I can run the docker container now.

**Comment by carlitoselmago** [comment]
Same happening to me, tried with two different computers and linux distros, both with nvidia gpus

**Comment by hanxiao** [comment]
closing for now as we are trying to provide an auto-build docker image in next few hours. feel free to open the issue if the new image still doesn't work.
