### ISSUE TITLE
DALL-E Mega taking forever (tstate-lock?)

### ISSUE THREAD

**Issue by iperezr** [jina-ai/dalle-flow#17]
Hey there!

Thanks for sharing the project. After updating dependencies, my run of the Colab gets stuck on step 1 trying to get 8 candidates from DALL-E Mega and GLID3 XL.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/42578882/168644743-ba32ce2d-6f01-4f77-b141-7bd3f5c0c658.png">

Any suggestions?

**Comment by Pro100rus32** [comment]
It's been over 40 minutes since the launch, but I'm still waiting)

**Comment by iperezr** [comment]
After 6 hours with no success I re-started the Colab and tried again, to no avail. Sadly can't give more details as to what might be causing the issue, since everything happens on Jina's server.

**Comment by tom-doerr** [comment]
It's my fault. I advertised my Dalle Flow Streamlit app on Reddit and multiple thousand people sent requests to Jina.ais server through my app. The traffic should die down in the next few hours. 
Some statistics: https://share.streamlit.io/tom-doerr/dalle_flow_streamlit/main?stats=true

**Comment by hanxiao** [comment]
yes, the traffic is booming and we only have one GPU to handle everything. At this stage, there is no plan to scale it up.


i don't think a badge can solve the traffic issue 😝 A more effective way is to deploy your own server by following the README, there is also a Docker image provided.

**Comment by tom-doerr** [comment]
As a quick fix I limited the number of request that are sent from the website to two per 5 minutes.

**Comment by spuliz** [comment]
@hanxiao I would happily set my own server but following the readme instructions is not enough. I think it needs to be improved by specifying exactly what other modules we need to install on top of the docker provided and what needs to be installed on the image of the instance (e.g. nvidia toolkit, etc..).
