### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by rdrlima** [jina-ai/dalle-flow#24]
the colab is not working for me since yesterday

 Traceback (most recent call last) ────────────────────────────╮
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882 in run_code  │
│                                                                                           │
│   2879 │   │   │   try:                                                                   │
│   2880 │   │   │   │   self.hooks.pre_run_code_hook()                                     │
│   2881 │   │   │   │   #rprint('Running code', repr(code_obj)) # dbg                      │
│ ❱ 2882 │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                  │
│   2883 │   │   │   finally:                                                               │
│   2884 │   │   │   │   # Reset our crash handler in place                                 │
│   2885 │   │   │   │   sys.excepthook = old_excepthook                                    │
│ <ipython-input-8-c8bf11265368>:1 in <module>                                              │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2117 in           │
│ run_cell_magic                                                                            │
│                                                                                           │
│   2114 │   │   │   stack_depth = 2                                                        │
│   2115 │   │   │   magic_arg_s = self.var_expand(line, stack_depth)                       │
│   2116 │   │   │   with self.builtin_trap:                                                │
│ ❱ 2117 │   │   │   │   result = fn(magic_arg_s, cell)                                     │
│   2118 │   │   │   return result                                                          │
│   2119 │                                                                                  │
│   2120 │   def find_line_magic(self, magic_name):                                         │
│ <decorator-gen-53>:2 in time                                                              │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magic.py:188 in <lambda>              │
│                                                                                           │
│   185 │   # This is a closure to capture the magic_kind.  We could also use a class,      │
│   186 │   # but it's overkill for just that one bit of state.                             │
│   187 │   def magic_deco(arg):                                                            │
│ ❱ 188 │   │   call = lambda f, *a, **k: f(*a, **k)                                        │
│   189 │   │                                                                               │
│   190 │   │   if callable(arg):                                                           │
│   191 │   │   │   # "Naked" decorator call (just @foo, no args)                           │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py:1193 in time      │
│                                                                                           │
│   1190 │   │   │   end = clock2()                                                         │
│   1191 │   │   else:                                                                      │
│   1192 │   │   │   st = clock2()                                                          │
│ ❱ 1193 │   │   │   exec(code, glob, local_ns)                                             │
│   1194 │   │   │   end = clock2()                                                         │
│   1195 │   │   │   out = None                                                             │
│   1196 │   │   wall_end = wtime()                                                         │
│ <timed exec>:6 in <module>                                                                │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/array/mixins/plot.py:337 in               │
│ plot_image_sprites                                                                        │
│                                                                                           │
│   334 │   │   :param show_progress: show a progresbar.                                    │
│   335 │   │   """                                                                         │
│   336 │   │   if not self:                                                                │
│ ❱ 337 │   │   │   raise ValueError(f'{self!r} is empty')                                  │
│   338 │   │                                                                               │
│   339 │   │   import matplotlib.pyplot as plt                                             │
│   340                                                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: <DocumentArray (length=0) at 140009031661712> is empty

**Comment by carrotbean** [comment]
I have the same issue.

**Comment by chawins** [comment]
The problem seems fixed now

**Comment by hanxiao** [comment]
upstream protobuf incident
