### ISSUE TITLE
Google colab throw out the following issues

### ISSUE THREAD

**Issue by Charlie-Xiaoqi** [jina-ai/dalle-flow#25]
when running the client.ipynb in colab, it throws out some errors for the following code:

`%%time

from docarray import Document

da = Document(text=prompt).post(server_url, parameters={'num_images': 8}).matches

da.plot_image_sprites(fig_size=(10,10), show_index=True)`

The error is:
`╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882 in run_code  │
│                                                                                           │
│   2879 │   │   │   try:                                                                   │
│   2880 │   │   │   │   self.hooks.pre_run_code_hook()                                     │
│   2881 │   │   │   │   #rprint('Running code', repr(code_obj)) # dbg                      │
│ ❱ 2882 │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                  │
│   2883 │   │   │   finally:                                                               │
│   2884 │   │   │   │   # Reset our crash handler in place                                 │
│   2885 │   │   │   │   sys.excepthook = old_excepthook                                    │
│ <ipython-input-27-c8bf11265368>:1 in <module>                                             │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2117 in           │
│ run_cell_magic                                                                            │
│                                                                                           │
│   2114 │   │   │   stack_depth = 2                                                        │
│   2115 │   │   │   magic_arg_s = self.var_expand(line, stack_depth)                       │
│   2116 │   │   │   with self.builtin_trap:                                                │
│ ❱ 2117 │   │   │   │   result = fn(magic_arg_s, cell)                                     │
│   2118 │   │   │   return result                                                          │
│   2119 │                                                                                  │
│   2120 │   def find_line_magic(self, magic_name):                                         │
│ <decorator-gen-53>:2 in time                                                              │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magic.py:188 in <lambda>              │
│                                                                                           │
│   185 │   # This is a closure to capture the magic_kind.  We could also use a class,      │
│   186 │   # but it's overkill for just that one bit of state.                             │
│   187 │   def magic_deco(arg):                                                            │
│ ❱ 188 │   │   call = lambda f, *a, **k: f(*a, **k)                                        │
│   189 │   │                                                                               │
│   190 │   │   if callable(arg):                                                           │
│   191 │   │   │   # "Naked" decorator call (just @foo, no args)                           │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py:1193 in time      │
│                                                                                           │
│   1190 │   │   │   end = clock2()                                                         │
│   1191 │   │   else:                                                                      │
│   1192 │   │   │   st = clock2()                                                          │
│ ❱ 1193 │   │   │   exec(code, glob, local_ns)                                             │
│   1194 │   │   │   end = clock2()                                                         │
│   1195 │   │   │   out = None                                                             │
│   1196 │   │   wall_end = wtime()                                                         │
│ <timed exec>:4 in <module>                                                                │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/document/mixins/sugar.py:92 in post       │
│                                                                                           │
│   89 │   │   from ... import DocumentArray                                                │
│   90 │   │                                                                                │
│   91 │   │   _tmp = DocumentArray(self)                                                   │
│ ❱ 92 │   │   return _tmp.post(*args, **kwargs)[0]                                         │
│   93                                                                                      │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/array/mixins/post.py:73 in post           │
│                                                                                           │
│   70 │   │   elif _scheme in ('grpc', 'http', 'ws', 'websocket'):                         │
│   71 │   │   │   from jina import Client                                                  │
│   72 │   │   │                                                                            │
│ ❱ 73 │   │   │   if _port:                                                                │
│   74 │   │   │   │   standardized_host += f':{_port}'                                     │
│   75 │   │   │                                                                            │
│   76 │   │   │   c = Client(host=standardized_host)                                       │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/__init__.py:199 in <module>                   │
│                                                                                           │
│   196                                                                                     │
│   197 # Client                                                                            │
│   198 from jina.clients import Client                                                     │
│ ❱ 199 from jina.orchestrate.flow.asyncio import AsyncFlow                                 │
│   200                                                                                     │
│   201 # Flow                                                                              │
│   202 from jina.orchestrate.flow.base import Flow                                         │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/orchestrate/flow/asyncio.py:2 in <module>     │
│                                                                                           │
│    1 from jina.clients.mixin import AsyncPostMixin                                        │
│ ❱  2 from jina.orchestrate.flow.base import Flow                                          │
│    3                                                                                      │
│    4                                                                                      │
│    5 class AsyncFlow(AsyncPostMixin, Flow):                                               │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/orchestrate/flow/base.py:65 in <module>       │
│                                                                                           │
│     62 )                                                                                  │
│     63 from jina.jaml import JAMLCompatible                                               │
│     64 from jina.logging.logger import JinaLogger                                         │
│ ❱   65 from jina.orchestrate.deployments import Deployment                                │
│     66 from jina.orchestrate.flow.builder import _hanging_deployments, allowed_levels     │
│     67 from jina.parsers import (                                                         │
│     68 │   set_client_cli_parser,                                                         │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/orchestrate/deployments/__init__.py:17 in     │
│ <module>                                                                                  │
│                                                                                           │
│    14 from jina.hubble.helper import replace_secret_of_hub_uri                            │
│    15 from jina.hubble.hubio import HubIO                                                 │
│    16 from jina.jaml.helper import complete_path                                          │
│ ❱  17 from jina.orchestrate.pods.container import ContainerPod                            │
│    18 from jina.orchestrate.pods.factory import PodFactory                                │
│    19 from jina.serve.networking import GrpcConnectionPool, host_is_local, in_docker      │
│    20                                                                                     │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/orchestrate/pods/__init__.py:15 in <module>   │
│                                                                                           │
│    12 from jina.helper import typename                                                    │
│    13 from jina.jaml import JAML                                                          │
│    14 from jina.logging.logger import JinaLogger                                          │
│ ❱  15 from jina.orchestrate.pods.helper import ConditionalEvent, _get_event               │
│    16 from jina.serve.runtimes.asyncio import AsyncNewLoopRuntime                         │
│    17                                                                                     │
│    18 __all__ = ['BasePod', 'Pod']                                                        │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/orchestrate/pods/helper.py:11 in <module>     │
│                                                                                           │
│     8 from jina.enums import GatewayProtocolType, PodRoleType                             │
│     9 from jina.hubble.helper import is_valid_huburi                                      │
│    10 from jina.hubble.hubio import HubIO                                                 │
│ ❱  11 from jina.serve.networking import GrpcConnectionPool                                │
│    12 from jina.types.request.control import ControlRequest                               │
│    13                                                                                     │
│    14 if TYPE_CHECKING:                                                                   │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/serve/networking.py:17 in <module>            │
│                                                                                           │
│     14 from jina.enums import PollingType                                                 │
│     15 from jina.importer import ImportExtensions                                         │
│     16 from jina.logging.logger import JinaLogger                                         │
│ ❱   17 from jina.proto import jina_pb2, jina_pb2_grpc                                     │
│     18 from jina.types.request import Request                                             │
│     19 from jina.types.request.control import ControlRequest                              │
│     20 from jina.types.request.data import DataRequest                                    │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/proto/jina_pb2.py:16 in <module>              │
│                                                                                           │
│    13 _sym_db = _symbol_database.Default()                                                │
│    14                                                                                     │
│    15                                                                                     │
│ ❱  16 import docarray.proto.docarray_pb2 as docarray__pb2                                 │
│    17 from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2         │
│    18 from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2       │
│    19 from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2 │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/proto/docarray_pb2.py:44 in <module>      │
│                                                                                           │
│    41 │     has_default_value=False, default_value=b"",                                   │
│    42 │     message_type=None, enum_type=None, containing_type=None,                      │
│    43 │     is_extension=False, extension_scope=None,                                     │
│ ❱  44 │     serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_c │
│    45 │   _descriptor.FieldDescriptor(                                                    │
│    46 │     name='shape', full_name='docarray.DenseNdArrayProto.shape', index=1,          │
│    47 │     number=2, type=13, cpp_type=3, label=3,                                       │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py:560 in __new__       │
│                                                                                           │
│    557 │   │   │   │   serialized_options=None,                                           │
│    558 │   │   │   │   has_default_value=True, containing_oneof=None, json_name=None,     │
│    559 │   │   │   │   file=None, create_key=None):  # pylint: disable=redefined-builtin  │
│ ❱  560 │     _message.Message._CheckCalledFromGeneratedFile()                             │
│    561 │     if is_extension:                                                             │
│    562 │   │   return _message.default_pool.FindExtensionByName(full_name)                │
│    563 │     else:                                                                        │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be 
regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing 
and will be much slower).

More information: 
https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates`

My colab is running Python 3.7.13
What is the JINA version you used before?
Thanks

**Comment by olivercoad** [comment]
Workaround is to run `!pip install protobuf==3.20.1` and restart runtime

**Comment by Charlie-Xiaoqi** [comment]
It works, thank you!
