### ISSUE TITLE
Can not generate 36 diffusion pic

### ISSUE THREAD

**Issue by Charlie-Xiaoqi** [jina-ai/dalle-flow#27]
Hi,
        In the markdown, for the below code it says:
`diffused = fav.post(f'{server_url}', parameters={'skip_rate': 0.5, 'num_images': 36}, target_executor='diffusion').matches

diffused.plot_image_sprites(fig_size=(10,10), show_index=True)`
"This will give 36 images based on the selected image. You may allow the model to improvise more by giving skip_rate a near-zero value, or a near-one value to force its closeness to the given image. The whole procedure takes about ~2 minutes."

But whatever num_images I tried (such as 36), it only generate 9 pics. Is that a bug?
Thanks
Charles

**Comment by spuliz** [comment]
same issue

**Comment by hanxiao** [comment]
free server restricts it to 9 per pathway, as described in the code
https://github.com/jina-ai/dalle-flow/blob/ba1c1e327a7daefbd09ae70109f74b34b1e27d0c/executors/dalle/executor.py#L15

You can host your own server and make it 36, 64, or however you want.
