### ISSUE TITLE
Dalle endpoint

### ISSUE THREAD

**Issue by tom-doerr** [jina-ai/dalle-flow#32]
Any chance to get an endpoint for generating images using just dalle and not glid-3? This would be useful for reducing the latency when generating the initial images.

**Comment by hanxiao** [comment]
you can refer to how 2nd step bypass dalle by using `target_executor` to do the same for bypassing diffusion.


My suggestion is to read docs.jina.ai  and try understand Flow API a bit more. This will help you a lot.

**Comment by tom-doerr** [comment]
Thank you for the tips!
