### ISSUE TITLE
Docker image connecting to demo-cas.jina.ai?

### ISSUE THREAD

**Issue by Quasimondo** [jina-ai/dalle-flow#36]
After several restarts I finally got the docker image to run locally on my machine. It was my impression that this image is supposed to be fully self-contained, but looking at the logs it reports:

`diffusion/rep-0@24 connected to demo-cas.jina.ai:2096`

Which seems to be set in flow.yml

So my question is whether this service is already provided by the docker image and this is just an oversight in the provided config file that it does not get used (since the docs suggest that) or if I have to run a dedicated clip-as-service instance if I want to avoid having to rely on external services?

**Comment by Mattie** [comment]
That's a demo server for https://github.com/jina-ai/clip-as-service -- it's pretty fast and responsive. I setup my own separate container for CAS to use in a private two server mode, but the demo server works pretty well.

**Comment by Curtis-64** [comment]
Thanks seen the same thing and was wondering!
