### ISSUE TITLE
Could I only use the DALLE?

### ISSUE THREAD

**Issue by yangkang2318** [jina-ai/dalle-flow#48]
Hello,this project is amazing, but can I just only use the DALLE due to my GPU limitations?

**Comment by hanxiao** [comment]
yes, you can. you can comment out every other component. However, we can't offer support, as we are not interested in supporting running DALLE. You may find other opensource projects for this purpose.

**Comment by yangkang2318** [comment]
> yes, you can. you can comment out every other component. However, we won't offer support, as **we are not interested in supporting DALLE**.
> 
> You may find other opensource projects for this purpose.

Thanks!
