### ISSUE TITLE
Would it be possible to generate an image in a different aspect ratio than 1:1?

### ISSUE THREAD

**Issue by 0xWTC** [jina-ai/dalle-flow#49]

**Comment by hanxiao** [comment]
yes.

However, think about it, what would be the best ratio then? 1:0.5? 0.618:1? 2:1, 3:1, 4:3? 0.7:1. Everyone has a very subjective ratio; or you can cut it yourself and then feed it as the input image for `/diffusion`. You will need to learn a bit [DocArray API](https://docarray.jina.ai) to know how to load image. There is no test for free-aspect image generation, however, so it may not work.

Finally supporting the non-1:1 aspect is not in the recent plan.
