### ISSUE TITLE
Do I just use a console window (command prompt) to enter this?

### ISSUE THREAD

**Issue by DataJuggler** [jina-ai/dalle-flow#50]
I see your instructions has things like: (I don't have Jina installed either for the same reason).

docker pull jinaai/dalle-flow:latest

I have never created a Docker container. Do I use Powershell, or just a command prompt, or what should I be entering these commands into?

I am a C# developer, and I know Python, but I don't have a clue from your instructions what to do.
Is there a YouTube video of how to setup the docker image for Dalle-Flow? I have the GPU for this, so I am anxious to try.

Thank you

**Comment by fogx** [comment]
check out [docker's get-started](https://docs.docker.com/get-started/) to learn more about docker images.

The section [run-in-docker](https://github.com/jina-ai/dalle-flow#run-in-docker) should be run inside your terminal.

After you've set up your server, you need to open the colab (client) and connect to the server, using the grcp address - probably `grpc://localhost:51005`

**Comment by DataJuggler** [comment]
I got further after I posted. I installed Docker, got the container downloaded and extracted. When I went to build it, I got some error and didn't know how to solve it and gave up.

Maybe you know this: 

Given these instructions below, do I replace ${USER} with my user name or leave these as ${USER}? I left them as is and got an error.

docker build --build-arg GROUP_ID=$(id -g ${USER}) --build-arg USER_ID=$(id -u ${USER}) -t jinaai/dalle-flow

Thank you for the reply. I didn't know what to do after the build fails. (I can't tell you the error because I got frustrated and uninstalled Docker, but may put it back on and try again some day).

**Comment by arjunsinha89** [comment]
> I see your instructions has things like: (I don't have Jina installed either for the same reason).
> 
> 
> 
> docker pull jinaai/dalle-flow:latest
> 
> 
> 
> I have never created a Docker container. Do I use Powershell, or just a command prompt, or what should I be entering these commands into?
> 
> 
> 
> I am a C# developer, and I know Python, but I don't have a clue from your instructions what to do.
> 
> Is there a YouTube video of how to setup the docker image for Dalle-Flow? I have the GPU for this, so I am anxious to try.
> 
> 
> 
> Thank you

**Comment by arjunsinha89** [comment]
- - - guy h- - - i okok ju```

h```tt get

**Comment by delgermurun** [comment]
https://github.com/jina-ai/dalle-flow/issues/107#issuecomment-1246525091
