### ISSUE TITLE
server is down i think, error message below

### ISSUE THREAD

**Issue by yesbroc** [jina-ai/dalle-flow#52]
ERROR  GRPCClient@60 gRPC error: StatusCode.UNAVAILABLE failed to connect [06/25/22 02:32:40]
       to all addresses                                                                      
       The ongoing request is terminated as the server is not available                      
       or closed already.                                                                    
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/jina/helper.py", line 1292, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/mixin.py", line 163, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/base/grpc.py", line 115, in _get_results
    raise ConnectionError(my_details) from None
ConnectionError: failed to connect to all addresses

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1306             try:
-> 1307                 return thread.result
   1308             except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)
7 frames
<decorator-gen-53> in time(self, line, cell, local_ns)

<timed exec> in <module>()

[/usr/local/lib/python3.7/dist-packages/jina/helper.py](https://localhost:8080/#) in run_async(func, *args, **kwargs)
   1310 
   1311                 raise BadClient(
-> 1312                     'something wrong when running the eventloop, result can not be retrieved'
   1313                 )
   1314         else:

BadClient: something wrong when running the eventloop, result can not be retrieved

**Comment by hanxiao** [comment]
solved
