### ISSUE TITLE
Can't pull the docker pull jinaai/dalle-flow:latest

### ISSUE THREAD

**Issue by Giupatamon** [jina-ai/dalle-flow#53]
The download starting after the command docker pull jinaai/dalle-flow:latest gets interrupted and it shows the error ERROR: unexpected EOF, I've tried downloading multiple times but it didn't work, any suggestion?

**Comment by Giupatamon** [comment]
PS C:\Users\Klara\Documents\dalle-flow\dalle\dalle-flow> docker pull jinaai/dalle-flow:latest
latest: Pulling from jinaai/dalle-flow
d5fd17ec1767: Already exists
d7c6ec6e1327: Already exists
943d01f4776a: Already exists
23025e0ea7d2: Already exists
8acc1c2b01b0: Already exists
894d0771aab5: Downloading [==================================================>]  1.012GB/1.012GB
8451e5a9bff2: Download complete
a6b5bd0a44ab: Waiting
364573d3ec98: Waiting
75b4e35cee13: Downloading [==================================================>]  1.363GB/1.363GB
ce2a1f714f22: Download complete
2490221e668e: Download complete
064bce5cdae3: Download complete
fc1a9b1d5bf0: Downloading [==================================================>]  7.762GB/7.762GB
a552334fac8a: Download complete
7abcaf16e2b7: Download complete
070e1264bbaf: Downloading [==================================================>]  5.728GB/5.728GB
unexpected EOF

**Comment by muchofire** [comment]
You are probably running into memory problems. You need more memory to store the entire model.

**Comment by muchofire** [comment]
Here is my entire process.

Requirements

Amazon AWS
Set up a g5.2xlarge instance on Amazon AWS. This is easy, and you should not be discouraged. You need to request an increase in the service quote to 8 vCPUs to launch it. You need to install this AMI from AWS, 'Deep Learning AMI GPU PyTorch 1.11.0 (Amazon Linux 2) 20220328' which has an identifier ami-023d5aa1ee956059c. I had EBS 300gb gp3 for the root disk, and g5.2xlarge with this AMI comes with a default instance store volume of 450gb. I also added an EFS file system.
To access this instance did I ssh by wsl on Windows 10 through VsCode. To ssh do you need a private key generated upon the creation of your EC2 instance, which was automatically downloaded to your local machine. You will get an error message using the raw .pem and will need to change the permissions related to this file with chmod 0400. However, to do this with wsl, windows 10 and vscode do you need to change the wsl.conf in /etc/wsl.conf. Just search the error you get up to find the right Stackoverflow
So after you have ssh into the instance will you see that the CUDA version installed is 11.5. That is actually a display bug, as you can check with the command 'nvidia-smi' that the CUDA version installed is indeed 11.6.
You will also be prompted to 'sudo yum update' at the first launch, so do that, as it won't cause issues.
Then you need to download the docker image of Dalle-flow with this command. docker pull jinaai/dalle-flow:latest
After this I tried to docker run, and got this error 'docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]. ERRO[0002] error waiting for container: context canceled' I resolved this by only using this command. 'sudo systemctl restart docker'.
Now, the source of your bug wrt being unable to import '/dalle/dalle-flow/executors/dalle/dm_helper.py' I have found comes from the faulty implementation of their provided command 'docker run -p 51005:51005 -v $HOME/.cache:/home/dalle/.cache --gpus all jinaai/dalle-flow' instead use this command 'docker run -p 51005:51005 --gpus all jinaai/dalle-flow'
To access the server using Google Colab, change your Security Group for your AWS instance to give access to the right TCP calls. I tested that it works if you allows 'ALL TCP' to have access to your instance, but this is definitely not recommended. I just did it to see how I could connect the Google Colab provided by Jina AI to this EC2 instance. You definitely do not want this as a permanent solution as bots can snipe your compute resources and expose security risks. Anyhow, if you just for the moment add a rule to the right security group for your instance, that alllows for ALL TCP, then you can simply change the 'server-url' inside the provided Google Colab in Github, from 'server_url = 'grpc://dalle-flow.jina.ai:51005' to server_url = 'grpc://[YOUR-AWS-PUBLIC-IP]:51005'

DONE.

**Comment by Giupatamon** [comment]
I'm using the local docker on my w10

**Comment by hanxiao** [comment]
potential reasons, sort by likelihood:
- network unstable
- out of disk space
- OOM
