### ISSUE TITLE
Colab notebook running forever

### ISSUE THREAD

**Issue by eluzzi5** [jina-ai/dalle-flow#6]
Was working perfectly yesterday morning, but this code block runs forever with no output:
%%time

from docarray import Document

da = Document(text=prompt).post(server_url, parameters={'num_images': 8}).matches

da.plot_image_sprites(fig_size=(10,10), show_index=True)

**Comment by hanxiao** [comment]
It was super crowded. But the server is continuously running

![aedf47c9136005d83709ec74a7b40d04](https://user-images.githubusercontent.com/2041322/167309437-745c1974-fdda-4450-9d81-87620c9511b1.gif)

One can deploy their own server as described here https://github.com/jina-ai/dalle-flow#server
