### ISSUE TITLE
How to select either DALLE-mega or GLID3 XL, but not both.

### ISSUE THREAD

**Issue by Sameer-connect-Hung-Linkedin** [jina-ai/dalle-flow#61]
The documents details that Dalle-Flow draws images from both  DALLE-mega and GLID3 XL, such that the number of images returned are always double 'num_images'. 

This is fine as you can select whatever image to store, however, if you are computing 100 images or 1000 images, then it becomes a significant computational waste when you recognize, depending on the prompt, that either DALLE-mega or GLID3 XL yields consistently poor results. 

How do you change it such that only DALLE-mega or GlLID3 XL is selecting for synthesis?

For reference, this is the line that generates your docarrays containing the image urls. Document(text=prompt).post(server_url, parameters={'num_images': 2}).matches

**Comment by AmericanPresidentJimmyCarter** [comment]
In `flow.yml`, comment out the executor you don't want, and then remove it from `needs` in the rerank flow.
