### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by Limbicnation** [jina-ai/dalle-flow#62]
`diffusion/rep-0@36167 fail to load file dependency                        [07/05/22 03:44:38]
⠙ Waiting dalle diffusion summary... ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 4/7 0:00:00ERROR  diffusion/rep-0@36167 FileNotFoundError(2, 'No such file or directory')   [07/05/22 03:44:38]
       during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization                     
        add "--quiet-error" to suppress the exception details  `
        
FileNotFoundError: [Errno 2] No such file or directory:                                      
       '../glid-3-xl/finetune.pt' `
       
       bert.pt
       finetune.pt
       kl-f8.pt
are located in `/dalle-flow/glid-3-xl`

**Comment by corporealfunk** [comment]
I have this issue when running the docker image as well

**Comment by corporealfunk** [comment]
Ok, so I'm not a docker expert, but this is a permissions issue about how the dalle user inside the docker container accesses mounted/shared volumes with the host. Inside the docker container, the user is UID 1000. That means that the folder being shared from the host had better be owned by UI 1000. Also, the documentation here in the README has the docker launch -v flag option backwards, in Docker, to mount volumes like that the flag is:

```-v host_src:container_dest```

That means, to launch a container from the image, you really need to run this:

```docker run -p 51005:51005 -it -v /home/ubuntu/.cache:/home/dalle/.cache --gpus all jinaai/dalle-flow```

On the local host the directory ```/home/ubuntu/.cache``` needs to be present and needs to be owned by UID 1000.

**Comment by delgermurun** [comment]
If prebuilt image doesn't work, try [building image locally](https://github.com/jina-ai/dalle-flow#build-it-yourself) by running below command 

```
docker build --build-arg GROUP_ID=$(id -g ${USER}) --build-arg USER_ID=$(id -u ${USER}) -t jinaai/dalle-flow .
```

then try to run by similar command
```
docker run -p 51005:51005 \
  -it \
  -v $HOME/.cache:/home/dalle/.cache \
  --gpus all \
  jinaai/dalle-flow
```

I believe this will resolve the issue, if not feel free to reopen.
