### ISSUE TITLE
I tried from colab research google page but get different results from example images

### ISSUE THREAD

**Issue by putuoka** [jina-ai/dalle-flow#69]
i try prompt: "a cubism painting donald trump happy cyberpunk" run on https://colab.research.google.com/github/jina-ai/dalle-flow/blob/main/client.ipynb

the results should like in the example readme this one:

![image](https://user-images.githubusercontent.com/20880839/180156808-5ec18084-4eef-4eae-880f-e5a934cfc85e.png)

but what i got is this different image

![image](https://user-images.githubusercontent.com/20880839/180157128-9102bee9-0289-4f08-a508-d047806ec387.png)

**Comment by hanxiao** [comment]
because you didn't finish the step 2 and step 3

**Comment by putuoka** [comment]
already do that but still not as smooth as example image. may be i need to try step-1 multiple times to get the near similar results. not sure
