### ISSUE TITLE
make "store" executor floating

### ISSUE THREAD

**Issue by delgermurun** [jina-ai/dalle-flow#76]
so it can run background asynchronously without blocking

**Comment by Andrei997** [comment]
Updated the DalleFlowStore executor to store generated images in the background using ThreadPoolExecutor (similarly to how `DocumentArray.apply()` would work).
Created PR at https://github.com/jina-ai/dalle-flow/pull/85

**Comment by delgermurun** [comment]
We can use https://docs.jina.ai/fundamentals/flow/add-executors/#floating-executors directly without manually running in thread.
