### ISSUE TITLE
Failed to connect to all addresses 

### ISSUE THREAD

**Issue by knorr3** [jina-ai/dalle-flow#82]
Hi,
I got the server running and tried it out. After executing the client:

```
doc = Document(text=prompt).post(server_url, parameters={'num_images': 8})
da = doc.matches
```

The server doesn't respond to the notebook and prints the following error:
```
DEBUG  diffusion/rep-0@24 recv DataRequest at / with id:     [08/11/22 06:41:47]
       4856d9e7b3334adf9aec568629267f62                                         
DEBUG  dalle/rep-0@23 recv DataRequest at / with id:         [08/11/22 06:41:47]
       4856d9e7b3334adf9aec568629267f62                                         
INFO   diffusion/rep-0@24 diffusion  ...                     [08/11/22 06:41:47]
INFO   dalle/rep-0@23 dalle 8 ...                            [08/11/22 06:41:47]
DEBUG  diffusion/rep-0@24 connected to demo-cas.jina.ai:2096 [08/11/22 06:41:47]
ERROR  diffusion/rep-0@24 gRPC error: StatusCode.UNAVAILABLE [08/11/22 06:42:27]
       failed to connect to all addresses                                       
       The ongoing request is terminated as the server is                       
       not available or closed already.                                         
ERROR  diffusion/rep-0@24 ConnectionError('failed to connect [08/11/22 06:42:27]
       to all addresses')                                                       
        add "--quiet-error" to suppress the exception                           
       details
```

Any idea what I can do? 

EDIT: I am running the latest docker image on OpenShift.

**Comment by derek-adair** [comment]
You have not configured your server_url properly would be my guess.

**Comment by delgermurun** [comment]
@knorr3 have you figured out the issue?

Maybe `demo-cas.jina.ai:2096` is not reachable for some reason.
If you have extra GPU memory, you could also try to run CLIP yourself https://github.com/jina-ai/dalle-flow#run-your-own-clip

**Comment by knorr3** [comment]
Ah, now I get it! It cannot connect to demo-cas.jina.ai because it has to use the proxy. 
The documentation of jina doesn't state any proxy settings for executors :( 

I tried your suggestion, but as I am in a container in a Kubernetes cluster, i cannot run docker inside it.

**Comment by delgermurun** [comment]
> It cannot connect to demo-cas.jina.ai because it has to use the proxy

Usually you don't need to do anything special if your machine has public internet access (outgoing traffic is allowed).

**Comment by knorr3** [comment]
I cannot access public internet without using the proxy. Is there any way I can configure jina to use the proxy?

**Comment by derek-adair** [comment]
Jina can be configured to point to a proxy from the CLI with the `--proxy` flag.  I've not really *used* k8s but i'm assuming you can set that flag on some entrypoint-like-thing.

**Comment by knorr3** [comment]
It does have a `--proxy` flag, but only for `jina gateway` and `jina client`.
There is no proxy flag for the `jina flow` command:

```
jina flow [-h] [--name] [--workspace] [--log-config] [--quiet] [--quiet-error]
          [--optout-telemetry] [--uses] [--env [KEY: VALUE [KEY: VALUE ...]]]
          [--inspect {HANG, REMOVE, COLLECT}]
```

**Comment by delgermurun** [comment]
>  i cannot run docker inside it.

Or you can run CLIP executor from its source code.
Try running with `uses: jinahub://CLIPTorchEncoder/latest-gpu`? (instead of `jinahub+docker`)

I don't know about `--proxy` flag, sorry. You can always ask from support channel in [Slack](https://slack.jina.ai/).

**Comment by knorr3** [comment]
I tried using `jinahub://` but it just terminated after downloading, again without any error. 

I think the most reasonable action at this point would be to get a proxy whitelisting for demo-cas.jina.ai.
Thank you very much for the support. I'll write again when there are any news or problems.
